include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Security
    avoid_print: true
    avoid_slow_async_io: true
    
    # Code quality
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    
    # Documentation
    public_member_api_docs: false
    
    # Error prevention
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    use_rethrow_when_possible: true
    
    # Performance
    avoid_unnecessary_containers: true
    avoid_widget_to_instance_variable: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  
  language:
    strict-casts: true
    strict-raw-types: true
