targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          exclude:
            - "lib/ui/**"
      json_serializable:json_serializable:
        generate_for:
          exclude:
            - "lib/ui/**"
      freezed:freezed:
        generate_for:
          exclude:
            - "lib/ui/**"
