// Mocks generated by Mockito 5.4.6 from annotations
// in ztd_password_manager/test/unit/blocs/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:ztd_password_manager/core/models/models.dart' as _i2;
import 'package:ztd_password_manager/services/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthCard_0 extends _i1.SmartFake implements _i2.AuthCard {
  _FakeAuthCard_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.AuthCard> get cards => (super.noSuchMethod(
        Invocation.getter(#cards),
        returnValue: <_i2.AuthCard>[],
      ) as List<_i2.AuthCard>);

  @override
  int get cardCount => (super.noSuchMethod(
        Invocation.getter(#cardCount),
        returnValue: 0,
      ) as int);

  @override
  _i2.AuthCard createCard({
    required _i2.AuthPayload? payload,
    required _i4.Uint8List? dek,
    required _i4.Uint8List? searchKey,
    required String? deviceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCard,
          [],
          {
            #payload: payload,
            #dek: dek,
            #searchKey: searchKey,
            #deviceId: deviceId,
          },
        ),
        returnValue: _FakeAuthCard_0(
          this,
          Invocation.method(
            #createCard,
            [],
            {
              #payload: payload,
              #dek: dek,
              #searchKey: searchKey,
              #deviceId: deviceId,
            },
          ),
        ),
      ) as _i2.AuthCard);

  @override
  _i2.AuthCard? updateCard({
    required String? cardId,
    required _i2.AuthPayload? newPayload,
    required _i4.Uint8List? dek,
    required _i4.Uint8List? searchKey,
    required String? deviceId,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #updateCard,
        [],
        {
          #cardId: cardId,
          #newPayload: newPayload,
          #dek: dek,
          #searchKey: searchKey,
          #deviceId: deviceId,
        },
      )) as _i2.AuthCard?);

  @override
  bool deleteCard(
    String? cardId,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCard,
          [
            cardId,
            deviceId,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool permanentlyDeleteCard(String? cardId) => (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteCard,
          [cardId],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.AuthCard> getActiveCards() => (super.noSuchMethod(
        Invocation.method(
          #getActiveCards,
          [],
        ),
        returnValue: <_i2.AuthCard>[],
      ) as List<_i2.AuthCard>);

  @override
  _i2.AuthCard? getCard(String? cardId) =>
      (super.noSuchMethod(Invocation.method(
        #getCard,
        [cardId],
      )) as _i2.AuthCard?);

  @override
  _i2.AuthPayload? decryptCard(
    _i2.AuthCard? card,
    _i4.Uint8List? dek,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #decryptCard,
        [
          card,
          dek,
        ],
      )) as _i2.AuthPayload?);

  @override
  String generateTOTP(_i2.AuthPayload? payload) => (super.noSuchMethod(
        Invocation.method(
          #generateTOTP,
          [payload],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateTOTP,
            [payload],
          ),
        ),
      ) as String);

  @override
  int getRemainingSeconds({int? period = 30}) => (super.noSuchMethod(
        Invocation.method(
          #getRemainingSeconds,
          [],
          {#period: period},
        ),
        returnValue: 0,
      ) as int);

  @override
  double getProgress({int? period = 30}) => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
          {#period: period},
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i2.AuthCard? importFromUri(
    String? uri,
    _i4.Uint8List? dek,
    _i4.Uint8List? searchKey,
    String? deviceId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #importFromUri,
        [
          uri,
          dek,
          searchKey,
          deviceId,
        ],
      )) as _i2.AuthCard?);

  @override
  List<_i2.AuthCard> importFromText(
    String? text,
    _i4.Uint8List? dek,
    _i4.Uint8List? searchKey,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromText,
          [
            text,
            dek,
            searchKey,
            deviceId,
          ],
        ),
        returnValue: <_i2.AuthCard>[],
      ) as List<_i2.AuthCard>);

  @override
  String? exportAsUri(
    _i2.AuthCard? card,
    _i4.Uint8List? dek,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #exportAsUri,
        [
          card,
          dek,
        ],
      )) as String?);

  @override
  String exportAllAsText(_i4.Uint8List? dek) => (super.noSuchMethod(
        Invocation.method(
          #exportAllAsText,
          [dek],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #exportAllAsText,
            [dek],
          ),
        ),
      ) as String);

  @override
  String exportAsJson(_i4.Uint8List? dek) => (super.noSuchMethod(
        Invocation.method(
          #exportAsJson,
          [dek],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #exportAsJson,
            [dek],
          ),
        ),
      ) as String);

  @override
  List<_i2.AuthCard> search(
    String? query,
    _i4.Uint8List? searchKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            query,
            searchKey,
          ],
        ),
        returnValue: <_i2.AuthCard>[],
      ) as List<_i2.AuthCard>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
