// Mocks generated by Mockito 5.4.6 from annotations
// in ztd_password_manager/test/unit/blocs/sync_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ztd_password_manager/core/sync/sync.dart' as _i2;
import 'package:ztd_password_manager/services/sync_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i3.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.SyncProgress> get syncProgress => (super.noSuchMethod(
        Invocation.getter(#syncProgress),
        returnValue: _i4.Stream<_i2.SyncProgress>.empty(),
      ) as _i4.Stream<_i2.SyncProgress>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addNode(_i2.WebDavNode? node) => (super.noSuchMethod(
        Invocation.method(
          #addNode,
          [node],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeNode(String? name) => (super.noSuchMethod(
        Invocation.method(
          #removeNode,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.WebDavNode>> getNodes() => (super.noSuchMethod(
        Invocation.method(
          #getNodes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.WebDavNode>>.value(<_i2.WebDavNode>[]),
      ) as _i4.Future<List<_i2.WebDavNode>>);

  @override
  _i4.Future<_i2.SyncResult> syncAll() => (super.noSuchMethod(
        Invocation.method(
          #syncAll,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
