// Mocks generated by Mockito 5.4.6 from annotations
// in ztd_password_manager/test/unit/services/vault_orchestration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;
import 'package:ztd_password_manager/core/crypto/crypto_facade.dart' as _i5;
import 'package:ztd_password_manager/core/crypto/crypto_service.dart' as _i6;
import 'package:ztd_password_manager/core/crypto/key_manager.dart' as _i11;
import 'package:ztd_password_manager/core/events/event_store.dart' as _i3;
import 'package:ztd_password_manager/core/models/models.dart' as _i9;
import 'package:ztd_password_manager/core/storage/database_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventStore_1 extends _i1.SmartFake implements _i3.EventStore {
  _FakeEventStore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCryptoFacade_3 extends _i1.SmartFake implements _i5.CryptoFacade {
  _FakeCryptoFacade_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArgon2Parameters_4 extends _i1.SmartFake
    implements _i6.Argon2Parameters {
  _FakeArgon2Parameters_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEncryptedData_5 extends _i1.SmartFake implements _i6.EncryptedData {
  _FakeEncryptedData_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryCursor_6 extends _i1.SmartFake implements _i2.QueryCursor {
  _FakeQueryCursor_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatch_7 extends _i1.SmartFake implements _i2.Batch {
  _FakeBatch_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i7.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.Database);

  @override
  _i3.EventStore get eventStore => (super.noSuchMethod(
        Invocation.getter(#eventStore),
        returnValue: _FakeEventStore_1(
          this,
          Invocation.getter(#eventStore),
        ),
      ) as _i3.EventStore);

  @override
  _i4.Future<void> initialize(String? encryptionKey) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [encryptionKey],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T> transaction<T>(
          _i4.Future<T> Function(_i2.Transaction)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<void> saveCard(
    _i9.PasswordCard? card, {
    _i2.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCard,
          [card],
          {#txn: txn},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.PasswordCard?> getCard(String? cardId) => (super.noSuchMethod(
        Invocation.method(
          #getCard,
          [cardId],
        ),
        returnValue: _i4.Future<_i9.PasswordCard?>.value(),
      ) as _i4.Future<_i9.PasswordCard?>);

  @override
  _i4.Future<List<_i9.PasswordCard>> getAllActiveCards() => (super.noSuchMethod(
        Invocation.method(
          #getAllActiveCards,
          [],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordCard>>.value(<_i9.PasswordCard>[]),
      ) as _i4.Future<List<_i9.PasswordCard>>);

  @override
  _i4.Future<List<_i9.PasswordCard>> getCardsUpdatedAfterHlc(_i9.HLC? hlc) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCardsUpdatedAfterHlc,
          [hlc],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordCard>>.value(<_i9.PasswordCard>[]),
      ) as _i4.Future<List<_i9.PasswordCard>>);

  @override
  _i4.Future<void> deleteCard(
    String? cardId,
    String? deviceId,
    String? eventId, {
    _i2.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCard,
          [
            cardId,
            deviceId,
            eventId,
          ],
          {#txn: txn},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> permanentlyDeleteCard(
    String? cardId, {
    _i2.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteCard,
          [cardId],
          {#txn: txn},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getCardCount() => (super.noSuchMethod(
        Invocation.method(
          #getCardCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i9.PasswordCard>> searchByBlindIndexes(
          List<String>? searchHashes) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByBlindIndexes,
          [searchHashes],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordCard>>.value(<_i9.PasswordCard>[]),
      ) as _i4.Future<List<_i9.PasswordCard>>);

  @override
  _i4.Future<List<_i9.PasswordCard>> searchByDecryptedContent(
    String? query,
    _i4.Future<String> Function(_i9.PasswordCard)? decryptFn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByDecryptedContent,
          [
            query,
            decryptFn,
          ],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordCard>>.value(<_i9.PasswordCard>[]),
      ) as _i4.Future<List<_i9.PasswordCard>>);

  @override
  _i4.Future<void> generateBlindIndexes(
    String? cardId,
    String? plaintext,
    _i10.Uint8List? searchKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBlindIndexes,
          [
            cardId,
            plaintext,
            searchKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getDatabaseSize() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseSize,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<String> exportDatabase(String? encryptionKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportDatabase,
          [encryptionKey],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportDatabase,
            [encryptionKey],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> importDatabase(String? backupPath) => (super.noSuchMethod(
        Invocation.method(
          #importDatabase,
          [backupPath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [CryptoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoService extends _i1.Mock implements _i6.CryptoService {
  MockCryptoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.CryptoFacade get facade => (super.noSuchMethod(
        Invocation.getter(#facade),
        returnValue: _FakeCryptoFacade_3(
          this,
          Invocation.getter(#facade),
        ),
      ) as _i5.CryptoFacade);

  @override
  _i10.Uint8List generateRandomBytes(int? length) => (super.noSuchMethod(
        Invocation.method(
          #generateRandomBytes,
          [length],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List deriveKEK(
    String? password,
    _i10.Uint8List? salt, {
    int? memoryKB = 65536,
    int? iterations = 3,
    int? parallelism = 4,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deriveKEK,
          [
            password,
            salt,
          ],
          {
            #memoryKB: memoryKB,
            #iterations: iterations,
            #parallelism: parallelism,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i6.Argon2Parameters benchmarkDevice() => (super.noSuchMethod(
        Invocation.method(
          #benchmarkDevice,
          [],
        ),
        returnValue: _FakeArgon2Parameters_4(
          this,
          Invocation.method(
            #benchmarkDevice,
            [],
          ),
        ),
      ) as _i6.Argon2Parameters);

  @override
  _i10.Uint8List generateDEK() => (super.noSuchMethod(
        Invocation.method(
          #generateDEK,
          [],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i6.EncryptedData encryptAESGCM(
    _i10.Uint8List? plaintext,
    _i10.Uint8List? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptAESGCM,
          [
            plaintext,
            key,
          ],
        ),
        returnValue: _FakeEncryptedData_5(
          this,
          Invocation.method(
            #encryptAESGCM,
            [
              plaintext,
              key,
            ],
          ),
        ),
      ) as _i6.EncryptedData);

  @override
  _i10.Uint8List decryptAESGCM(
    _i6.EncryptedData? encryptedData,
    _i10.Uint8List? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptAESGCM,
          [
            encryptedData,
            key,
          ],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i6.EncryptedData encryptString(
    String? plaintext,
    _i10.Uint8List? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptString,
          [
            plaintext,
            key,
          ],
        ),
        returnValue: _FakeEncryptedData_5(
          this,
          Invocation.method(
            #encryptString,
            [
              plaintext,
              key,
            ],
          ),
        ),
      ) as _i6.EncryptedData);

  @override
  String decryptString(
    _i6.EncryptedData? encryptedData,
    _i10.Uint8List? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptString,
          [
            encryptedData,
            key,
          ],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #decryptString,
            [
              encryptedData,
              key,
            ],
          ),
        ),
      ) as String);

  @override
  _i10.Uint8List hkdfSha256(
    _i10.Uint8List? ikm, {
    _i10.Uint8List? salt,
    _i10.Uint8List? info,
    int? length = 32,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hkdfSha256,
          [ikm],
          {
            #salt: salt,
            #info: info,
            #length: length,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List hmacSha256(
    _i10.Uint8List? key,
    _i10.Uint8List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hmacSha256,
          [
            key,
            data,
          ],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  String hmacSha256String(
    String? key,
    String? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hmacSha256String,
          [
            key,
            data,
          ],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #hmacSha256String,
            [
              key,
              data,
            ],
          ),
        ),
      ) as String);

  @override
  bool constantTimeEquals(
    _i10.Uint8List? a,
    _i10.Uint8List? b,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #constantTimeEquals,
          [
            a,
            b,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool constantTimeEqualsHex(
    String? a,
    String? b,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #constantTimeEqualsHex,
          [
            a,
            b,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Uint8List sha256Hash(_i10.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #sha256Hash,
          [data],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  String sha256String(String? data) => (super.noSuchMethod(
        Invocation.method(
          #sha256String,
          [data],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #sha256String,
            [data],
          ),
        ),
      ) as String);

  @override
  List<String> generateBlindIndexes(
    String? plaintext,
    _i10.Uint8List? searchKey, {
    int? minTokenLength = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBlindIndexes,
          [
            plaintext,
            searchKey,
          ],
          {#minTokenLength: minTokenLength},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String bytesToHex(_i10.Uint8List? bytes) => (super.noSuchMethod(
        Invocation.method(
          #bytesToHex,
          [bytes],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #bytesToHex,
            [bytes],
          ),
        ),
      ) as String);

  @override
  _i10.Uint8List hexToBytes(String? hex) => (super.noSuchMethod(
        Invocation.method(
          #hexToBytes,
          [hex],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  void clearBuffer(_i10.Uint8List? buffer) => super.noSuchMethod(
        Invocation.method(
          #clearBuffer,
          [buffer],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [KeyManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyManager extends _i1.Mock implements _i11.KeyManager {
  MockKeyManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isUnlocked => (super.noSuchMethod(
        Invocation.getter(#isUnlocked),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize(String? masterPassword) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [masterPassword],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> unlock(String? masterPassword) => (super.noSuchMethod(
        Invocation.method(
          #unlock,
          [masterPassword],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void lock() => super.noSuchMethod(
        Invocation.method(
          #lock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i10.Uint8List?> getSearchKey() => (super.noSuchMethod(
        Invocation.method(
          #getSearchKey,
          [],
        ),
        returnValue: _i4.Future<_i10.Uint8List?>.value(),
      ) as _i4.Future<_i10.Uint8List?>);

  @override
  _i4.Future<String?> getDeviceId() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> changeMasterPassword(
    String? oldPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeMasterPassword,
          [
            oldPassword,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i10.Uint8List?> rotateDEK(String? masterPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotateDEK,
          [masterPassword],
        ),
        returnValue: _i4.Future<_i10.Uint8List?>.value(),
      ) as _i4.Future<_i10.Uint8List?>);

  @override
  _i4.Future<bool> isInitialized() => (super.noSuchMethod(
        Invocation.method(
          #isInitialized,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> exportEmergencyKit(String? masterPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportEmergencyKit,
          [masterPassword],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> importEmergencyKit(String? kitJson) => (super.noSuchMethod(
        Invocation.method(
          #importEmergencyKit,
          [kitJson],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [EventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventStore extends _i1.Mock implements _i3.EventStore {
  MockEventStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> appendEvent(
    _i9.PasswordEvent? event, {
    _i2.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendEvent,
          [event],
          {#txn: txn},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> appendEvents(
    List<_i9.PasswordEvent>? events, {
    _i2.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendEvents,
          [events],
          {#txn: txn},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.PasswordEvent?> getEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i9.PasswordEvent?>.value(),
      ) as _i4.Future<_i9.PasswordEvent?>);

  @override
  _i4.Future<List<_i9.PasswordEvent>> getEventsForCard(String? cardId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsForCard,
          [cardId],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordEvent>>.value(<_i9.PasswordEvent>[]),
      ) as _i4.Future<List<_i9.PasswordEvent>>);

  @override
  _i4.Future<List<_i9.PasswordEvent>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordEvent>>.value(<_i9.PasswordEvent>[]),
      ) as _i4.Future<List<_i9.PasswordEvent>>);

  @override
  _i4.Future<List<_i9.PasswordEvent>> getEventsAfterHlc(_i9.HLC? hlc) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsAfterHlc,
          [hlc],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordEvent>>.value(<_i9.PasswordEvent>[]),
      ) as _i4.Future<List<_i9.PasswordEvent>>);

  @override
  _i4.Future<List<_i9.PasswordEvent>> getUnsyncedEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedEvents,
          [],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordEvent>>.value(<_i9.PasswordEvent>[]),
      ) as _i4.Future<List<_i9.PasswordEvent>>);

  @override
  _i4.Future<void> markEventsAsSynced(
    List<String>? eventIds, {
    _i2.Transaction? txn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markEventsAsSynced,
          [eventIds],
          {#txn: txn},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.HLC?> getLatestHlc() => (super.noSuchMethod(
        Invocation.method(
          #getLatestHlc,
          [],
        ),
        returnValue: _i4.Future<_i9.HLC?>.value(),
      ) as _i4.Future<_i9.HLC?>);

  @override
  _i4.Future<int> getEventCount() => (super.noSuchMethod(
        Invocation.method(
          #getEventCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i9.PasswordEvent>> getEventsByType(_i9.EventType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByType,
          [type],
        ),
        returnValue:
            _i4.Future<List<_i9.PasswordEvent>>.value(<_i9.PasswordEvent>[]),
      ) as _i4.Future<List<_i9.PasswordEvent>>);

  @override
  _i4.Future<void> deleteEventsBeforeHlc(_i9.HLC? hlc) => (super.noSuchMethod(
        Invocation.method(
          #deleteEventsBeforeHlc,
          [hlc],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createSnapshot({
    required int? version,
    required Map<String, dynamic>? stateJson,
    required _i9.HLC? eventRangeStart,
    required _i9.HLC? eventRangeEnd,
    String? previousSnapshotId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSnapshot,
          [],
          {
            #version: version,
            #stateJson: stateJson,
            #eventRangeStart: eventRangeStart,
            #eventRangeEnd: eventRangeEnd,
            #previousSnapshotId: previousSnapshotId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.Snapshot?> getLatestSnapshot() => (super.noSuchMethod(
        Invocation.method(
          #getLatestSnapshot,
          [],
        ),
        returnValue: _i4.Future<_i3.Snapshot?>.value(),
      ) as _i4.Future<_i3.Snapshot?>);

  @override
  _i4.Future<_i3.Snapshot?> getSnapshotByVersion(int? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSnapshotByVersion,
          [version],
        ),
        returnValue: _i4.Future<_i3.Snapshot?>.value(),
      ) as _i4.Future<_i3.Snapshot?>);

  @override
  _i4.Future<List<_i3.Snapshot>> getAllSnapshots() => (super.noSuchMethod(
        Invocation.method(
          #getAllSnapshots,
          [],
        ),
        returnValue: _i4.Future<List<_i3.Snapshot>>.value(<_i3.Snapshot>[]),
      ) as _i4.Future<List<_i3.Snapshot>>);

  @override
  _i4.Future<void> pruneSnapshots(int? keepCount) => (super.noSuchMethod(
        Invocation.method(
          #pruneSnapshots,
          [keepCount],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastSync(_i9.HLC? hlc) => (super.noSuchMethod(
        Invocation.method(
          #updateLastSync,
          [hlc],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.HLC?> getLastSyncHlc() => (super.noSuchMethod(
        Invocation.method(
          #getLastSyncHlc,
          [],
        ),
        returnValue: _i4.Future<_i9.HLC?>.value(),
      ) as _i4.Future<_i9.HLC?>);

  @override
  _i4.Future<int> getPendingCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Transaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransaction extends _i1.Mock implements _i2.Transaction {
  MockTransaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.Database);

  @override
  _i4.Future<void> execute(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> rawInsert(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawInsert,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
          {
            #nullColumnHack: nullColumnHack,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<Map<String, Object?>>>.value(
            <Map<String, Object?>>[]),
      ) as _i4.Future<List<Map<String, Object?>>>);

  @override
  _i4.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, Object?>>>.value(
            <Map<String, Object?>>[]),
      ) as _i4.Future<List<Map<String, Object?>>>);

  @override
  _i4.Future<_i2.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQueryCursor,
          [
            sql,
            arguments,
          ],
          {#bufferSize: bufferSize},
        ),
        returnValue: _i4.Future<_i2.QueryCursor>.value(_FakeQueryCursor_6(
          this,
          Invocation.method(
            #rawQueryCursor,
            [
              sql,
              arguments,
            ],
            {#bufferSize: bufferSize},
          ),
        )),
      ) as _i4.Future<_i2.QueryCursor>);

  @override
  _i4.Future<_i2.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryCursor,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
            #bufferSize: bufferSize,
          },
        ),
        returnValue: _i4.Future<_i2.QueryCursor>.value(_FakeQueryCursor_6(
          this,
          Invocation.method(
            #queryCursor,
            [table],
            {
              #distinct: distinct,
              #columns: columns,
              #where: where,
              #whereArgs: whereArgs,
              #groupBy: groupBy,
              #having: having,
              #orderBy: orderBy,
              #limit: limit,
              #offset: offset,
              #bufferSize: bufferSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.QueryCursor>);

  @override
  _i4.Future<int> rawUpdate(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawUpdate,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> rawDelete(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawDelete,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i2.Batch batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeBatch_7(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i2.Batch);
}
